# Site settings
title: SimpleSAMLphp
email: support@feide.no
description: SimpleSAMLphp** is an award-winning application written in native PHP that deals with authentication. It
  implements support for multiple protocols, most notably SAML, OpenID or OAuth.
baseurl: ""
url: "https://simplesamlphp.github.io"
twitter_username: simplesamlphp
github_username:  simplesamlphp
plugins_dir: ./_plugins

# Build settings
markdown: kramdown

jekyll_get:
  - data: latest
    json: 'https://api.github.com/repos/simplesamlphp/simplesamlphp/releases/latest'
    cache: false
